### ISSUE TITLE
Search for zika fails

### ISSUE THREAD

**Issue by joeb37** [CS599-MEDLINE/pubminer-web-app#105]
Searching for `zika` has reliably produced 53 result rows for quite a while now. On Monday evening it is failing completely.  The error is:
```
dynamo batchGet error: TypeError: Cannot read property 'reduce' of undefined
(node:20677) UnhandledPromiseRejectionWarning: AppError: Internal error. Please try again.
    at docClient.batchGet.promise.then.catch.err (/Users/Joe/Developer/cscie599/pmc-oa-test/services/DemographicsService.js:72:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:20677) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20677) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by freshottr** [comment]
addressed by #106
